id = "modelica"
name = "Modelica"
version = "0.0.1"
schema_version = 1
authors = ["Antoine Gautier <agautier@solamen.fr>"]
description = "Highlighting for Modelica language"
repository = "https://github.com/AntoineGautier/zed-modelica"
languages = ["languages/modelica"]

[grammars.modelica]
repository = "https://github.com/AntoineGautier/tree-sitter-modelica"
commit = "823792840892240fd9cc5e8f25c58bc5db371ecc"
