name = "Modelica"
grammar = "modelica"
path_suffixes = ["mo"]
line_comments = ["// "]
tab_size = 2
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "/*", end = " */", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]

# Indent if the line starts with a keyword that must be followed by one or more parameters *or*
# if the line starts and ends with `else` *or*
# if the line ends with an opening parentheses or bracket.
increase_indent_pattern = "^\\s*(function|if|else\\s+if|while|for)\\b|^\\s*(else)\\s*$|[\\(\\[\\{]\\s*$"

# Dedent if the line starts with a keyword that ends a block or with a closing parentheses or bracket.
decrease_indent_pattern = "^\\s*(else|end)\\b|^\\s*[\\)\\]\\}]"
